spring:
  datasource:
    autoCommit: false
    url: jdbc:postgresql://localhost:5432/db_controly
    username: usr_controly
    password: controly123
    driver-class-name: org.postgresql.Driver
    hiraki:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: controly
      password: controly
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
logging:
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"
server:
  servlet:
    session:
      persistent: false
hibernate:
  connection:
    autocommit: false